# This file is used to build the gRPC service.
#
# Anyscale command:
# anyscale service rollout -f service.yaml

name: grpc-service
cluster_env: grpc-cluster-env:1
cloud: anyscale_v2_default_cloud
config:
  protocols:
    grpc:
      enabled: true  # Enable gRPC protocol.
      service_names:
        - userdefinedprotos.  # The name of the gRPC service in your .proto file.
ray_serve_config:
  grpc_options:
    port: 9000
    grpc_servicer_functions:
      - user_defined_protos_pb2_grpc.add_UserDefinedServiceServicer_to_server
      - user_defined_protos_pb2_grpc.add_ImageClassificationServiceServicer_to_server

  applications:
    - name: app1
      route_prefix: /
      import_path: deployment:h
      runtime_env: { }

    - name: app2
      route_prefix: /foo
      import_path: deployment:h2
      runtime_env: { }

    - name: app3
      route_prefix: /bar
      import_path: deployment:g
      runtime_env: { }

    - name: app4
      route_prefix: /baz
      import_path: deployment:g2
      runtime_env: { }

    - name: app5
      route_prefix: /fastapi
      import_path: deployment:app
      runtime_env: { }
