cloud_id: cld_xyz # TODO: fill in your cloud id
head_node_type:
  name: head_node
  instance_type: m5.2xlarge
worker_node_types:
- name: cpu_worker
  instance_type: m5.4xlarge
  min_workers: 0
  max_workers: 10
  use_spot: true
- name: gpu_worker
  instance_type: g4dn.4xlarge
  min_workers: 0
  max_workers: 10
  use_spot: true